components:
  schemas:
    LikeResponse:
      type: object
      description: ''
      properties:
        entryId:
          format: int64
          type: integer
        likeAt:
          format: date-time
          type: string
        likeId:
          type: string
          format: uuid
    LikeCountResponse:
      type: object
      properties:
        count:
          type: integer
          format: int64
        exists:
          type: boolean
info:
  title: OpenAPI definition
  version: 0.0.1-SNAPSHOT
openapi: 3.0.1
paths:
  /likes:
    get:
      operationId: getLikes
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/LikeResponse'
              examples:
                example-1: {}
          description: OK
      tags:
        - like-controller
      description: ''
      summary: Get all Likes
  '/likes/{entryId}':
    delete:
      operationId: deleteLike
      parameters:
        - in: path
          name: entryId
          required: true
          schema:
            format: int64
            type: integer
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
      tags:
        - like-controller
      summary: Delete Likes for an entry
    get:
      operationId: getLike
      parameters:
        - in: path
          name: entryId
          required: true
          schema:
            format: int64
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LikeCountResponse'
          description: OK
        '404':
          description: Not Found
      tags:
        - like-controller
      summary: Get Likes for an entry
    post:
      operationId: postLike
      parameters:
        - in: path
          name: entryId
          required: true
          schema:
            format: int64
            type: integer
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LikeResponse'
          description: OK
      tags:
        - like-controller
      summary: Post a Like to an entry
servers:
  - description: Generated server url
    url: 'https://like.dev.ik.am'
